### ISSUE TITLE
iOS: Passcode is not asking when deleting an account

### ISSUE THREAD

**Issue by julialips** [tonkeeper/wallet#27]
### Bug Type

Security

### Reproduction steps

1. Open Tonkeeper
2. Log in to your wallet or create new one
3. Set a password
4. Open 'Wallet' tab
5. Go to the background/close the app and return back in the app
     **Actual result:** The passcode is not asking. So, there is a chance that someone possible to get access
6. Open 'Settings' and 'Delete account' feature
7. Confirm deletion by clicking the 'Delete account and data' button in the pop-up

### Actual result

The account successfully deleted.
The password is not asked for deleting the account. 
So user may lose the access to their account.

### Expected result

The passcode should be asked for deleting account feature how it works for sending, viewing recovery phrase.

### Suggested Severity

High

### Device

    Device: iPhone 11
    OS: 14.3

### Additional Context

Not sure about this issue, do not understand the difference between 'Log out' and 'Delete account' feature.
Also don't see  'Delete account' on Android app. 
But in most cases, 'Delete account' features is something important and require PIN code

**Comment by olyaMay** [comment]
Hi! Button "Delete account" is visible only at iOS devices. We did it because rules of AppleStore sad that. Also "Delete account" in the Tonkeeper works like «Log out». You can not delete something in blockchain. You can get access to your wallet at the every moment with your secret phrase.
So, I think you don't need to enter password for logout.
